### ISSUE TITLE
Recomprar skins en la tienda

### ISSUE THREAD

**Issue by ManuelRodriguezBonete** [Cannibal-Coconut/MozzaRace#1]
- Impacto: Medio
- Plataforma: ordenador
- Descripción: tras jugar un par de partidas y tener monedas, fui a la tienda y compré la mitad de las skins. Jugué un par más de partidas y volví a la tienda para comprar alguna más y vi que podía recomprar skins que ya tenía.
- Pasos para reproducirlo
1.  Tener monedas para comprar skins y comprar alguna en la tienda
2. Jugar una partida
3. Volver a la tienda y comprobar que puedes recomprar una skin que ya tienes

**Comment by dexaxi** [comment]
Solucionado, había un problema con la serialización de assets en relación con el servidor.
