### ISSUE TITLE
Al morir, la segunda comanda permanece en la siguiente partida 

### ISSUE THREAD

**Issue by MarioSimon** [Cannibal-Coconut/MozzaRace#10]
- Prioridad: Media
- Plataforma: PC y Móvil
- Descripción: Cuando se llega al punto de la partida en el que el jugador tiene que atender dos comandas a la vez, si muere se llevará la segunda (con el mismo progreso que tuviera al morir) a la siguiente partida si no sale al menú principal. 
- Pasos para reproducirlo:
   
    1  Empezar una partida.
    2. Avanzar hasta que empiecen a llegar varias comandas a la vez (no estoy seguro de si esto ocurre por número de comandas completas o por puntuación; en mi caso suele bastar con completar 3-4 recetas).
    3. (opcional) Coger un ingrediente de la segunda comanda.
    4. Morir.
    5. Volver a jugar sin salir al menú principal.
 
PD: la primera comanda de la siguiente partida aparecerá pocos segundos despues de comenzar, lo que otorgará una segunda comanda, permitiendo replicar esta ocurrencia más facilmente después de hacerlo una primera vez.

**Comment by dexaxi** [comment]
Solucionado!
