### ISSUE TITLE
Control deja de funcionar en ordenador

### ISSUE THREAD

**Issue by Frollo24** [Cannibal-Coconut/MozzaRace#2]
- Impacto: Alto
- Plataforma: Ordenador
- Descripción: Jugando en el modo fuera de pantalla completa, al hacer click en la página y dar a la barra espaciadora para saltar la página hace scroll automáticamente hacia abajo y el personaje deja de saltar
- Pasos para reproducirlo:

1. Comenzar a jugar en ordenador
2. No activar la pantalla completa
3. Hacer click fuera de la pantalla de juego
4. Presionar la barra espaciadora

**Comment by dexaxi** [comment]
Esto es problema del navegador, no del juego, pasa en todos. Sin embargo, es cierto que normalmente se pausa al clicar fuera y en este caso no, se mirará de modificar el template.
