### ISSUE TITLE
Cambio de idioma 

### ISSUE THREAD

**Issue by Asgardr** [Cannibal-Coconut/MozzaRace#3]
- Impacto: Bajo
- Plataforma: PC y movil
- Descripción: Al cambiar de idioma de ingles a español, varios textos se mantienen en ingles (Volume, Spanish, English). Además de eso, al estar en español, los acentos modifican las letras haciendolas mas grandes y sin italica. Por último, al entrar por primera vez en la pantalla de ajustes el boton Otros, antes de cambiar el idioma aparece como Miscelaneos y despues de cambiarlo otra vez al ingles aparece como Others.
- Pasos para reproducirlo:

1. Entrar en el menu de ajustes
2. Cambiar el idioma de ingles a español
3. Cambiar el idioma de español a ingles
4. Volver a la pantalla principal

**Comment by ManuelRodriguezBonete** [comment]
Esto también ocurre con la tienda, cuando entras por primera vez está en español, pero si juegas una partida y vuelves, se pone otra vez en inglés.

**Comment by dexaxi** [comment]
Arreglado! Ahora el idioma se cambia correctamente en todas partes, además, al cambiarlo se reescala correctamente.
