### ISSUE TITLE
No se puede restaurar la skin por defecto

### ISSUE THREAD

**Issue by Frollo24** [Cannibal-Coconut/MozzaRace#4]
- Impacto: Medio
- Plataforma: Ordenador
- Descripción: Después de comprar una skin en la tienda, no se puede restaurar la skin por defecto si no quieres jugar con la skin por defecto
- Pasos para reproducirlo:

1. Comprar una skin en la tienda
2. Cambiar la skin

**Comment by dexaxi** [comment]
Arreglado.
