### ISSUE TITLE
Sin lista de ingredientes al volver a jugar

### ISSUE THREAD

**Issue by Asgardr** [Cannibal-Coconut/MozzaRace#5]
- Impacto: Alto
- Plataformas: PC y movil
- Descripción: Despues de morir en una run e intentar volver a jugar desde la pantalla de muerte, la lista de ingredientes no aparece hasta pasados unos 5 segundos, no permitiendote coger ingredientes durante ese rato.
- Pasos para reproducirlo:

1. Jugar una partida
2. Morir
3. Volver a jugar desde el menu de muerte

**Comment by dexaxi** [comment]
Se ha retirado la penalización!
