### ISSUE TITLE
Crasheo completo del juego

### ISSUE THREAD

**Issue by Asgardr** [Cannibal-Coconut/MozzaRace#6]
- Impacto: Critico
- Plataforma: PC
- Descripción: De vez en cuando, el juego se bloquea completamente y no se puede seguir jugando.
- Pasos para reproducirlo: No tenemos claro como ocurre o como volver a reproducirlo pero nos ha ocurrido varias veces al lanzar la pizza hacia atras y coger un objeto fuera de pantalla.
![Bug 1](https://user-images.githubusercontent.com/73491797/143057697-78bdf256-fea3-4c99-8528-b44842fe245c.PNG)

**Comment by ManuelRodriguezBonete** [comment]
Este error me ha ocurrido de una forma parecida, no necesariamente al saltar o al lanzar la pizza, también me ha ocurrido cuando completas una comanda.

**Comment by Frollo24** [comment]
A mí también me ocurrió, tengo la sospecha de que tiene que ver con el rodillo porque las veces que me ha ocurrido había un rodillo en pantalla.
![BugFreeze](https://user-images.githubusercontent.com/57634169/143492739-aa339835-179a-4e49-b074-64ce22bcb212.PNG)

**Comment by dexaxi** [comment]
Finiquitado, gracias por la ayuda!
