### ISSUE TITLE
Misma mision en la tienda sin poder saltártela.

### ISSUE THREAD

**Issue by DavidGanfornina** [Cannibal-Coconut/MozzaRace#7]
Impacto: Bajo
 Plataforma: PC
 Descripción: Aparece la misma misión disponible 3 veces y aún teniendo dinero no te las puedes saltar pulsando en el botón.
 Pasos para reproducirlo: Hacer y saltarte las misiones hasta que aparece 3 veces la misma.

**Comment by dexaxi** [comment]
Solucionado! Era culpa de un singleton mal configurado!
