### ISSUE TITLE
Controles de música no funcionan correctamente

### ISSUE THREAD

**Issue by Frollo24** [Cannibal-Coconut/MozzaRace#8]
- Impacto: Bajo
- Plataforma: Ordenador y móvil
- Descripción: Al ajustar la música desde los ajustes, esta se vuelve prácticamente inaudible al poner el slider sobre el 50% o menos, mientras que en transiciones cortas de entre el 90% y el 100% el volumen crece demasiado
- Pasos para reproducirlo:

1. Entrar en los ajustes de sonido
2. Ajustar los niveles de sonido

**Comment by ManuelRodriguezBonete** [comment]
Esto es un error el cual habíamos detectado en nuestro grupo también, el volumen al 50% está demasiado bajo (no se escucha nada) y a partir de un 80% está demasiado alto.
Solo con los valores predeterminados (entre un 60% y un 80%) se escucha de forma decente.

**Comment by dexaxi** [comment]
Arreglado! Ahora el volumen es logarítmico.
